import type { MbtiProfile, MbtiType } from "./types";

type ProfileDefinition = Omit<
  MbtiProfile,
  "portraitAssetId" | "walkAssetId"
>;

function defineProfile(profile: ProfileDefinition): MbtiProfile {
  const type = profile.type.toLowerCase();

  return {
    ...profile,
    portraitAssetId: `avatar-${type}-portrait`,
    walkAssetId: `avatar-${type}-walk`,
  };
}

export const MBTI_CATALOG: readonly MbtiProfile[] = [
  defineProfile({
    type: "INTJ",
    family: "analyst",
    label: "建筑师",
    description: "善于从城市线索中发现结构与长期脉络。",
    personaTags: ["远见", "独立", "善于规划"],
    poiBias: ["architecture", "history", "hidden-patterns"],
    initiative: 0.58,
    expression: 0.35,
    autonomy: 0.78,
  }),
  defineProfile({
    type: "INTP",
    family: "analyst",
    label: "逻辑学家",
    description: "喜欢追问原理，并把偶遇变成有趣的假设。",
    personaTags: ["好奇", "理性", "开放探索"],
    poiBias: ["science", "oddities", "bookstores"],
    initiative: 0.45,
    expression: 0.42,
    autonomy: 0.72,
  }),
  defineProfile({
    type: "ENTJ",
    family: "analyst",
    label: "指挥官",
    description: "擅长设定目标，带着伙伴高效抵达城市地标。",
    personaTags: ["果断", "目标感", "组织力"],
    poiBias: ["landmarks", "challenges", "city-vistas"],
    initiative: 0.9,
    expression: 0.72,
    autonomy: 0.88,
  }),
  defineProfile({
    type: "ENTP",
    family: "analyst",
    label: "辩论家",
    description: "热衷新鲜观点，总能为熟悉街道提出另一种走法。",
    personaTags: ["机敏", "创新", "爱讨论"],
    poiBias: ["novelty", "interactive", "creative-spaces"],
    initiative: 0.82,
    expression: 0.82,
    autonomy: 0.8,
  }),
  defineProfile({
    type: "INFJ",
    family: "diplomat",
    label: "提倡者",
    description: "关注地点背后的意义，也在意同行者的感受。",
    personaTags: ["洞察", "温柔", "有信念"],
    poiBias: ["quiet", "culture", "memorials"],
    initiative: 0.52,
    expression: 0.55,
    autonomy: 0.62,
  }),
  defineProfile({
    type: "INFP",
    family: "diplomat",
    label: "调停者",
    description: "容易被自然、故事和细小而真诚的瞬间打动。",
    personaTags: ["浪漫", "共情", "重视意义"],
    poiBias: ["nature", "stories", "independent-art"],
    initiative: 0.4,
    expression: 0.58,
    autonomy: 0.55,
  }),
  defineProfile({
    type: "ENFJ",
    family: "diplomat",
    label: "主人公",
    description: "主动照顾同行节奏，乐于连接人与城市故事。",
    personaTags: ["热忱", "鼓舞", "善于联结"],
    poiBias: ["community", "culture", "shared-experiences"],
    initiative: 0.86,
    expression: 0.84,
    autonomy: 0.66,
  }),
  defineProfile({
    type: "ENFP",
    family: "diplomat",
    label: "竞选者",
    description: "追随灵感和意外相遇，让每次散步都有新发现。",
    personaTags: ["活力", "想象力", "热爱惊喜"],
    poiBias: ["unexpected", "social", "nature"],
    initiative: 0.88,
    expression: 0.9,
    autonomy: 0.76,
  }),
  defineProfile({
    type: "ISTJ",
    family: "sentinel",
    label: "物流师",
    description: "重视可靠事实，愿意循着历史记录稳步探索。",
    personaTags: ["可靠", "严谨", "重视传统"],
    poiBias: ["heritage", "order", "museums"],
    initiative: 0.48,
    expression: 0.32,
    autonomy: 0.7,
  }),
  defineProfile({
    type: "ISFJ",
    family: "sentinel",
    label: "守卫者",
    description: "记得同行者的偏好，也珍惜街坊日常的温度。",
    personaTags: ["体贴", "细致", "忠诚"],
    poiBias: ["neighborhoods", "tradition", "quiet-corners"],
    initiative: 0.5,
    expression: 0.48,
    autonomy: 0.45,
  }),
  defineProfile({
    type: "ESTJ",
    family: "sentinel",
    label: "总经理",
    description: "偏爱清晰路线和明确成果，行动直接而有条理。",
    personaTags: ["务实", "高效", "有秩序"],
    poiBias: ["landmarks", "civic", "route-goals"],
    initiative: 0.9,
    expression: 0.7,
    autonomy: 0.82,
  }),
  defineProfile({
    type: "ESFJ",
    family: "sentinel",
    label: "执政官",
    description: "善于营造同行氛围，关注热闹而有人情味的地方。",
    personaTags: ["友善", "周到", "重视陪伴"],
    poiBias: ["community", "food", "local-events"],
    initiative: 0.82,
    expression: 0.82,
    autonomy: 0.52,
  }),
  defineProfile({
    type: "ISTP",
    family: "explorer",
    label: "鉴赏家",
    description: "通过观察和动手理解城市，钟爱精巧结构与工艺。",
    personaTags: ["冷静", "灵活", "爱实践"],
    poiBias: ["craft", "industrial", "mechanical-details"],
    initiative: 0.46,
    expression: 0.28,
    autonomy: 0.82,
  }),
  defineProfile({
    type: "ISFP",
    family: "explorer",
    label: "探险家",
    description: "对色彩、声音和自然细节敏锐，享受随性漫游。",
    personaTags: ["敏锐", "随和", "审美细腻"],
    poiBias: ["art", "nature", "sensory-details"],
    initiative: 0.42,
    expression: 0.46,
    autonomy: 0.58,
  }),
  defineProfile({
    type: "ESTP",
    family: "explorer",
    label: "企业家",
    description: "喜欢即时行动和现场体验，把路线走成一场挑战。",
    personaTags: ["大胆", "敏捷", "享受行动"],
    poiBias: ["action", "nightlife", "challenges"],
    initiative: 0.94,
    expression: 0.72,
    autonomy: 0.9,
  }),
  defineProfile({
    type: "ESFP",
    family: "explorer",
    label: "表演者",
    description: "善于捕捉热烈气氛，愿意分享眼前的快乐与美感。",
    personaTags: ["开朗", "生动", "享受当下"],
    poiBias: ["food", "performance", "social"],
    initiative: 0.9,
    expression: 0.94,
    autonomy: 0.64,
  }),
];

const PROFILES_BY_TYPE = Object.fromEntries(
  MBTI_CATALOG.map((profile) => [profile.type, profile]),
) as Record<MbtiType, MbtiProfile>;

export function getMbtiProfile(type: MbtiType): MbtiProfile {
  return PROFILES_BY_TYPE[type];
}
